# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    assignees:
      - kernelsam
    cooldown:
      default-days: 21
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: pip
    assignees:
      - docktermj
    cooldown:
      default-days: 21
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    assignees:
      - arawinters
    cooldown:
      default-days: 21
    directory: /
    schedule:
      interval: daily
